### ISSUE TITLE
No factory functions emitted

### ISSUE THREAD

**Issue by harryjubb** [homebound-team/graphql-typescript-factories#19]
Hi 👋   

Really cool project! Am having some trouble getting it to work locally though.

My `graphql-codegen.yml` looks like

```yaml
overwrite: true
schema: "plugin-graphql-schema.json"
documents: "src/assets/**/*.graphql"
config:
  scalars:
    # Graphene passes down datetimes as ISO strings
    DateTime: ISO8601DateString
    UUID: string
    JSONString: string
  maybeValue: T | null | undefined
generates:
  src/assets/js/generated/graphql.ts:
    plugins:
      - add:
          content: "/* eslint-disable */"
      - add:
          content: "type ISO8601DateString = string;"
      - add:
          content: "export type DeepPartial<T> = { [P in keyof T]?: T[P] extends object ? DeepPartial<T[P]> : T[P]; };"
      # Base TS types
      - "typescript"
      # Generates types from our schema
      - "typescript-operations"
      # Generates TS from .graphql files
      - "typescript-document-nodes"
      # Generates Vue Apollo specific typings
      - "typescript-vue-apollo"
      # Generates factory methods to mock / stub API responses in tests
      - "@homebound/graphql-typescript-factories"
    config:
      addDocBlocks: true
      withCompositionFunctions: false
```

I run

```graphql-codegen --config graphql-codegen.yml```

Types as usual are generated fine, however the only addition to my previously generated types is:

```typescript
let nextFactoryIds: Record<string, number> = {};

export function resetFactoryIds() {
  nextFactoryIds = {};
}

function nextFactoryId(objectName: string): string {
  const nextId = nextFactoryIds[objectName] || 1;
  nextFactoryIds[objectName] = nextId + 1;
  return String(nextId);
}
```

Without any factory functions.

Any help appreciated!
